# Generated by Django 3.1.1 on 2020-09-08 07:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history', models.CharField(default='someHistory', max_length=300)),
                ('visualAcuity', models.CharField(default='some', max_length=300)),
                ('ExternalEyeExamination', models.CharField(default='Examination', max_length=300)),
                ('functionalTest', models.CharField(default='Test', max_length=300)),
                ('refractionDetails', models.CharField(default='Details', max_length=300)),
                ('Diagnosis', models.CharField(default='Diagnosis', max_length=300)),
            ],
        ),
        migrations.RemoveField(
            model_name='patient',
            name='fullname',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='location',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='mobile',
        ),
        migrations.AddField(
            model_name='patient',
            name='address',
            field=models.CharField(default='sample', max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='age',
            field=models.CharField(default='sample address', max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='date_registered',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='occupation',
            field=models.CharField(default='occupation', max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='patientName',
            field=models.CharField(default='patientName', max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='phoneNumber',
            field=models.CharField(default='phoneNumber', max_length=100),
        ),
        migrations.DeleteModel(
            name='Prescription',
        ),
        migrations.AddField(
            model_name='clinicalinfo',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient'),
        ),
    ]
