# Generated by Django 3.1.1 on 2020-09-08 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_auto_20200908_1025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clinicalinfo',
            old_name='Diagnosis',
            new_name='diagnosis',
        ),
    ]
