# Generated by Django 3.1.1 on 2020-09-09 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_auto_20200908_1028'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(max_length=100)),
                ('count', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=200)),
            ],
        ),
    ]
